### ISSUE TITLE
Filtering out SysWOW64

### ISSUE THREAD

**Issue by iosonogio** [wietze/windows-dll-hijacking#5]
Many thanks for these resources! In the SIGMA rule `possible_windows_dll_hijacking.yml` this path should/could be filtered out: `C:\Windows\SysWOW64\`

That is:

```
    filter:
        EventID: 7
        ImageLoaded:
            - "C:\\Windows\\WinSxS\\*"
            - "C:\\Windows\\System32\\*"
            - "C:\\Windows\\SysWOW64\\*"
```
